project:
  type: website
  output-dir: ../output
  resources:
    - assets/

website:
  title: "Slides Bruno"

format:
  revealjs:
    theme: night
    transition: fade
    slide-number: true
    chalkboard: true
