---
title: "Aula 1 - Números Binários"
author: ["Dr. Bruno Pereira Santos", "Caio Sereno Santos Rebouças"]
subtitle: "MATA38 - Projeto de Circuitos Lógicos <br> <a href='../'>Página Inicial</a>"
lang: "pt-BR"
format: 
  revealjs:
    transition: fade
    slide-number: true
    incremental: true
    theme: [default, ../assets/global/theme.scss]
    navigation-mode: linear
    controls-layout: bottom-right
    include-after-body: ../assets/global/breadcrumb.html
    footer: "MATA38 - Projeto de Circuitos Lógicos"
---

# Relembrando Sinais

-   Na vida real temos sinais analógicos
-   Para processar sinais analógicos em sistemas digitais temos que seguir o seguinte fluxo:

```{=html}
<!-- 
Adicionar gráfico de fluxo de conversão de sinais analógicos para processamento de sistemas digitais
-->
```

# Intuição:<br> Switch & Bits

## Vantagens dos sistemas digitais

-   Redução de Ruido
-   Uso de menos banda
-   Criptografia
-   Eficiência para transmissões de longa distância

## Níveis e Precisão

-   Quanto mais precisão de medida, mais níveis são necessários

## Switch/Bits

-   Podemos representar um bit com um switch
-   Circuito Aberto = $0$
-   Circuito Fechado = $1$

```{=html}
<!-- Adicionar minicircuito com um switch -->

```

## Bits e níveis
- Quanto mais bits, mais níveis podem ser representados
- Representação com 2 switches:

::: {.fragment}
::: {.list-table}
- - $SW_{1}$
  - $SW_{2}$
- - OFF
  - OFF
- - OFF
  - ON
- - ON
  - OFF
- - ON
  - ON
:::
:::

## Bits e Níveis
- Generalizando: $n = 2^{m}$
  - $n :=$ # de nívies
  - $m :=$ # de switches


::: {.callout-note .fragment}
## Exemplo

$$
m = 3 \to n = 2^{3} = 8 \text{ níveis}
$$
:::


# Números Binários

## Representação dos números
- Já conhecemos o sistema decimal:
  - $(327)_{10} = 3 \cdot 10^{2} + 2 \cdot 10^{1} + 7 \cdot 10^{0}$ 
- No sistema binário:
  - Um dígito é chamado de *bit*
    - $(234)_{10} \text{ tem 3 dígitos}$   
    - $(101)_{2} \text{ tem 3 bits}$   

## Representar quantidades
- Um número de 2 bits tem 4 possiveis representações:
  - $\uparrow \text{SW} = \uparrow \text{ bits} = \uparrow \text{ mais precisão}$
  - Logo é possível representar 4 valores diferentes com a representação

## Bits e Bytes
- Um conjunto de $8$ *bits* $(b)$ forma um *byte* $(B)$ 
$$
\begin{aligned}
8 \text{ bits} = 1 \text{ byte} \\
\end{aligned}
$$

- É possível adicionar sufixos para a representação

# 

::: {.columns width="100%"}

:::::: {.column width="25%"}

```{mermaid}
flowchart TD
BYTE --> |x1024| MEGABYTE
MEGABYTE --> |x1024| GIGABYTE
GIGABYTE --> |x1024| TERABYTE

TERABYTE --> |/1024| GIGABYTE
GIGABYTE --> |/1024| MEGABYTE
MEGABYTE --> |/1024| BYTE  
```

::::::

:::::: {.column width="80%"}

::: {style="font-size: 0.78em; line-height: 1.25"}
| Unidade | Símbolo | Equivalência |
| :--- | :---: | :--- |
| Bit | b | 1 bit |
| Byte | B | 8 bits |
| Kilobit | Kb | $10^3$ bits  |
| Kilobyte | KB | $2^{10}$ bytes (1.024 B) |
| Megabit | Mb | $10^6$ bits |
| Megabyte | MB | $2^{20}$ bytes (1.024 KB) |
| Gigabit | Gb | $10^9$ bits |
| Gigabyte | GB | $2^{30}$ bytes (1.024 MB) |
| Terabit | Tb | $10^{12}$ bits |
| Terabyte | TB | $2^{40}$ bytes (1.024 GB) |

: {tbl-colwidths="[5,5,90]"}

:::

::::::

:::


