---
title: "Aula 2 - Álgebra Booleana"
author: ["Dr. Bruno Pereira Santos", "Caio Sereno Santos Rebouças"]
subtitle: "MATA38 - Projeto de Circuitos Lógicos <br> <a href='../'>Página Inicial</a>"
lang: "pt-BR"
format: 
  revealjs:
    transition: fade
    slide-number: true
    incremental: true
    theme: [default, ../assets/global/theme.scss]
    navigation-mode: linear
    controls-layout: bottom-right
    include-after-body: ../assets/global/breadcrumb.html
    footer: "MATA38 - Projeto de Circuitos Lógicos"
---

# Introdução
## Informações Gerais: 
- Introduzido pelo matemático [George Boole](https://pt.wikipedia.org/wiki/George_Boole){preview-link="true"}
- Conjunto de regras usadas para uma dada expressão lógica sem mudar sua funcionalidade

<!-- Remover o breadcrumb  nesse slide -->


::: {.fragment}
::: {.callout-tip}

## Exemplo:

$$
F = \underbrace{\underbrace{\bar{A}B}_{\text{= and}}+ \underbrace{BC}_{\text{= and}} + \underbrace{ABC}_{\text{= and}}}_{\text{= or}}
$$

:::
:::

## Uso
- Usamos algebra booleana para nº de variáveis pequenas (até 3 variáveis)
- Para nº maiores se usa o **Mapa de Karnaugh**

## Razões
- Reduzir:
  - nº de portas
  - Custo
  - Calor nos componentes



## Exemplo: Levar ou não o guarda-chuva

```{mermaid}
flowchart LR
  A((A)) --> |Rain| OR
  B((B)) --> |Rain Forecast| OR
  C((C)) --> |Take car| NOT
  OR --> |A+B| AND
  NOT --> |~C| AND
  AND --> |Take umbrella| Y((Y))
```


# Operações Básicas
## Not
- Operação complementar
- Sempre inverte a entrada
- $\bar{A} = A' = NOT(A)$

::: fragment

::: {.list-table}

- - $A$
  - $\bar{A}$
- - 0
  - 1
- - 1
  - 0

:::

:::

## And
- Saída alta apenas se ambas entradas altas

::: fragment

::: {.list-table}

- - $A$
  - $B$
  - $A \cdot B$
- - 0
  - 0
  - 0
- - 0
  - 1
  - 0
- - 1
  - 0
  - 0
- - 1
  - 1
  - 1

:::

:::

## Or
- Saída alta com qualquer entrada alta

::: fragment

::: {.list-table}

- - $A$
  - $B$
  - $A + B$
- - 0
  - 0
  - 0
- - 0
  - 1
  - 1
- - 1
  - 0
  - 1
- - 1
  - 1
  - 1

:::

:::


# Propriedades
## Lei Distributiva: 
$$
\begin{aligned}
A \cdot (B + C) &= A \cdot B + A \cdot C \\
A + (B \cdot C) &= (A+B) \cdot (A+C)
\end{aligned}
$$


::: {.columns}

::: {.column .callout-note}
## Exemplo
$$
\begin{aligned}
A + \bar{A}B = &\underbrace{(A+\bar{A})} \cdot
(A+B) \\
&= 1 \cdot (A+B) \\
&= A+B
\end{aligned}
$$

:::

::: {.column .callout-note}
## Importante
$$
\begin{aligned}
& A + \bar{A}B = A+B \\
& \bar{A} + AB = \bar{A}+B
\end{aligned}
$$

:::

:::

## Lei Comutativa: 
$$
\begin{aligned}
A+B &= B+A \\
A \cdot B &= B \cdot A
\end{aligned}
$$

## Lei Associativa:
$$
\begin{aligned}
(A+B)+C &= A+(B+C) \\
(A \cdot B) \cdot C &= A \cdot (B \cdot C)
\end{aligned}
$$

## Lei De Morgan:
$$
\begin{aligned}
\overline{(A+B)} &= \bar{A} \cdot \bar{B} \\
\overline{(A \cdot B)} &= \bar{A} + \bar{B}
\end{aligned}
$$


::: {.fragment .list-table}

* - $A$
  - $B$
  - $A+B$
  - $\overline{A+B}$
  - $\bar{A}$
  - $\bar{B}$
  - $\bar{A} \cdot \bar{B}$
* - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
* - 0
  - 1
  - 1
  - 0
  - 1
  - 0
  - 0
* - 1
  - 0
  - 1
  - 0
  - 0
  - 1
  - 0
* - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0

:::

# Lei de Precedência
1. NOT
2. AND
3. OR

# {style="display: flex; justify-content: center; align-items: center; width: 100%; height: 100%"}
<video data-autoplay loop controls width="100%" style="border-radius: 12px; box-shadow: 0 4px 24px rgba(0,0,0,0.5);">
  <source src="../assets/aula-2/reducao.mp4" type="video/mp4">
</video>

## Regras
- Complemento: $(\overline{\overline{A}}) = A$
- AND:
  * $A \cdot A = A$
  * $A \cdot 0 = 0$
  * $A \cdot 1 = A$
  * $A \cdot \bar{A} = 0$

## Regras
- OR:
  * $A + A = A$
  * $A + 0 = A$
  * $A + 1 = 1$
  * $A + \bar{A} = 1$